/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.CultistPlayer;
import napakalaki.Monster;
import napakalaki.Napakalaki;
import napakalaki.Prize;

/**
 *
 * @author Lenovo
 */
public class MonsterView extends javax.swing.JPanel {
    //Atributo
    private Monster monsterModel;
    private Napakalaki napakalakiModel;
    
    //Setter
    public void setMonster(Monster aMonster){
        monsterModel = aMonster;
        this.name.setText(monsterModel.getName());
        Prize price = new Prize(monsterModel.getLevelsGained(), monsterModel.getTreasuresGained());
        this.prize.setPrize(price);
        this.badConsequence.SetBadConsequence(monsterModel.getBadConsequence());
        
        if(napakalakiModel.getCurrentPlayer() instanceof CultistPlayer)
            this.level.setText(Integer.toString(monsterModel.getCombatLevelAgainstCultistPlayer()));
        else
            this.level.setText(Integer.toString(monsterModel.getCombatLevel()));
        
        repaint();
    }
    
    public void setNapakalaki(Napakalaki aNapakalaki){
        napakalakiModel = aNapakalaki;
    }
    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        name = new javax.swing.JTextArea();
        prize = new GUI.PrizeView();
        levelPanel = new javax.swing.JPanel();
        level = new javax.swing.JLabel();
        BadConsequencePanel = new javax.swing.JPanel();
        badConsequence = new GUI.BadConsequenceView();

        name.setEditable(false);
        name.setBackground(new java.awt.Color(153, 153, 153));
        name.setColumns(14);
        name.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setLineWrap(true);
        name.setRows(2);
        name.setWrapStyleWord(true);
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name.setSelectionColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(name);

        prize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        levelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        levelPanel.setForeground(new java.awt.Color(0, 0, 0));

        level.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        level.setForeground(new java.awt.Color(0, 0, 0));
        level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level.setText("10");
        level.setToolTipText("");
        level.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nivel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout levelPanelLayout = new javax.swing.GroupLayout(levelPanel);
        levelPanel.setLayout(levelPanelLayout);
        levelPanelLayout.setHorizontalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        levelPanelLayout.setVerticalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(level)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BadConsequencePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BadConsequencePanel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout BadConsequencePanelLayout = new javax.swing.GroupLayout(BadConsequencePanel);
        BadConsequencePanel.setLayout(BadConsequencePanelLayout);
        BadConsequencePanelLayout.setHorizontalGroup(
            BadConsequencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BadConsequencePanelLayout.createSequentialGroup()
                .addComponent(badConsequence, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        BadConsequencePanelLayout.setVerticalGroup(
            BadConsequencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BadConsequencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(badConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BadConsequencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(levelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(levelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BadConsequencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BadConsequencePanel;
    private GUI.BadConsequenceView badConsequence;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel level;
    private javax.swing.JPanel levelPanel;
    private javax.swing.JTextArea name;
    private GUI.PrizeView prize;
    // End of variables declaration//GEN-END:variables
}
