/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.CombatResult;
import napakalaki.Napakalaki;

/**
 *
 * @author Lenovo
 */
public class NapakalakiView extends javax.swing.JFrame {
    
    //Atributo
    private Napakalaki napakalakiModel;
    
    //Setter
    public void setNapakalaki(Napakalaki aModel){
        napakalakiModel = aModel;
        
        this.currentPlayer.setNapakalaki(napakalakiModel);
        this.currentMonster.setNapakalaki(napakalakiModel);
        this.currentPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
        this.currentMonster.setMonster(napakalakiModel.getCurrentMonster());
        this.combatResult.setText(" ");
        
        currentMonster.setVisible(false);
        meetMonster.setEnabled(true);
        combat.setEnabled(false);
        nextTurn.setEnabled(false);
        
        //Del Player
        currentPlayer.setDiscardAllTreasures(false);
        currentPlayer.setDiscardTreasures(false);
        currentPlayer.setSteal(false);
        
        repaint();
    }
    
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        setTitle("Napakalaki Game");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combatResultPanel = new javax.swing.JPanel();
        combatResult = new javax.swing.JLabel();
        monsterPanel = new javax.swing.JPanel();
        currentMonster = new GUI.MonsterView();
        meetMonster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        nextTurn = new javax.swing.JButton();
        currentPlayer = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        combatResultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Resultado del combate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        combatResult.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        combatResult.setForeground(new java.awt.Color(0, 0, 0));
        combatResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        combatResult.setText("GANASTE");
        combatResult.setToolTipText("");

        javax.swing.GroupLayout combatResultPanelLayout = new javax.swing.GroupLayout(combatResultPanel);
        combatResultPanel.setLayout(combatResultPanelLayout);
        combatResultPanelLayout.setHorizontalGroup(
            combatResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combatResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        combatResultPanelLayout.setVerticalGroup(
            combatResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combatResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        monsterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Monstruo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        monsterPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        monsterPanel.setMaximumSize(new java.awt.Dimension(350, 398));
        monsterPanel.setMinimumSize(new java.awt.Dimension(350, 398));
        monsterPanel.setPreferredSize(new java.awt.Dimension(350, 398));

        javax.swing.GroupLayout monsterPanelLayout = new javax.swing.GroupLayout(monsterPanel);
        monsterPanel.setLayout(monsterPanelLayout);
        monsterPanelLayout.setHorizontalGroup(
            monsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monsterPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(currentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monsterPanelLayout.setVerticalGroup(
            monsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monsterPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(currentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        meetMonster.setBackground(new java.awt.Color(255, 255, 255));
        meetMonster.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        meetMonster.setForeground(new java.awt.Color(0, 0, 0));
        meetMonster.setText("Mostrar Monstruo");
        meetMonster.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        meetMonster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterActionPerformed(evt);
            }
        });

        combat.setBackground(new java.awt.Color(204, 0, 0));
        combat.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        combat.setForeground(new java.awt.Color(255, 255, 255));
        combat.setText("¡¡COMBATIR!!");
        combat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        combat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        nextTurn.setBackground(new java.awt.Color(0, 153, 51));
        nextTurn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        nextTurn.setForeground(new java.awt.Color(0, 0, 0));
        nextTurn.setText("PASAR TURNO");
        nextTurn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        nextTurn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nextTurn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(meetMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combat, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(combatResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(monsterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meetMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(nextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combatResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monsterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        CombatResult resultado;
        resultado = napakalakiModel.developCombat();
        
        if(resultado == CombatResult.WIN)
            this.combatResult.setText("GANASTE");
        else if(resultado == CombatResult.LOSE)
            this.combatResult.setText("PERDISTE");
        else if(resultado == CombatResult.LOSEANDCONVERT)
            this.combatResult.setText("CONVERSION A SECTARIO");
        else{
            this.combatResult.setText("¡¡GANASTE EL JUEGO!!");
            new Fin(this, true).setVisible(true);
        }
        
        currentPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
        combat.setEnabled(false);
        nextTurn.setEnabled(true);
        
        currentPlayer.setMakeVisible(true);
        currentPlayer.setDiscardTreasures(true);
        currentPlayer.setDiscardAllTreasures(true);
        if(napakalakiModel.getCurrentPlayer().canISteal())
            currentPlayer.setSteal(true);
    }//GEN-LAST:event_combatActionPerformed

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        if(napakalakiModel.nextTurn())
            setNapakalaki(napakalakiModel);
    }//GEN-LAST:event_nextTurnActionPerformed

    private void meetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterActionPerformed
        meetMonster.setEnabled(false);
        currentMonster.setVisible(true);
        combat.setEnabled(true);
        currentPlayer.setMakeVisible(false);
    }//GEN-LAST:event_meetMonsterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JLabel combatResult;
    private javax.swing.JPanel combatResultPanel;
    private GUI.MonsterView currentMonster;
    private GUI.PlayerView currentPlayer;
    private javax.swing.JButton meetMonster;
    private javax.swing.JPanel monsterPanel;
    private javax.swing.JButton nextTurn;
    // End of variables declaration//GEN-END:variables
}
