/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import napakalaki.CultistPlayer;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author Lenovo
 */
public class PlayerView extends javax.swing.JPanel {
    //Atributo
    private Player playerModel;
    private Napakalaki napakalakiModel;
    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void setPlayer(Player aPlayer){
        playerModel = aPlayer;
        this.name.setText(playerModel.getName());
        this.nivelVar.setText(Integer.toString(playerModel.getLevels()));
        this.combatLevelVar.setText(Integer.toString(playerModel.getCombatLevel()));
        this.enemyVar.setText(playerModel.getEnemyName());
        this.pendingBadConsequenceVar.setPendingBadConsequence(playerModel.getPendingBadConsequence());
        
        if(playerModel.canISteal())
            this.canIStealVar.setText("Si");
        else
            this.canIStealVar.setText("No");
        
        if(playerModel.isDead())
            this.deathVar.setText("Muerto");
        else
            this.deathVar.setText("Vivo");
        
        
        if( playerModel instanceof CultistPlayer)
            this.cultistPlayerVar.setText("Si");
        else
            this.cultistPlayerVar.setText("No");
        
        this.numCultistVar.setText(Integer.toString(CultistPlayer.getTotalCultistPlayers()));
        
        
        this.fillTreasurePanel(visibleTreasures,playerModel.getVisibleTreasures());
        this.fillTreasurePanel(hiddenTreasures,playerModel.getHiddenTreasures());

        
        repaint();
        revalidate();
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al panel
        for (Treasure t : aList) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    public void setNapakalaki(Napakalaki aNapakalaki){
        napakalakiModel = aNapakalaki;
        repaint();
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        // Se recorren los tesoros que contiene el panel,
        // almacenando en un vector aquellos que están seleccionados.
        // Finalmente se devuelve dicho vector.
        
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
            tv = (TreasureView) c;
            if ( tv.isSelected() )
                output.add ( tv.getTreasure() );
        }
        
        return output;
    }
    
    public void setMakeVisible(boolean set){
        makeVisible.setEnabled(set);
    }

    public void setDiscardTreasures(boolean set) {
        discardTreasures.setEnabled(set);
    }
    
    public void setDiscardAllTreasures(boolean set){
        discardAllTreasures.setEnabled(set);
    }
    
    public void setSteal(boolean set){
        stealTreasure.setEnabled(set);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        Atributos = new javax.swing.JPanel();
        nivel = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        nivelVar = new javax.swing.JLabel();
        combatLevelVar = new javax.swing.JLabel();
        death = new javax.swing.JLabel();
        deathVar = new javax.swing.JLabel();
        canISteal = new javax.swing.JLabel();
        canIStealVar = new javax.swing.JLabel();
        enemy = new javax.swing.JLabel();
        enemyVar = new javax.swing.JLabel();
        pendingBadConsequence = new javax.swing.JPanel();
        pendingBadConsequenceVar = new GUI.PendingBadConsequenceView();
        cultistInfo = new javax.swing.JPanel();
        cultistPlayer = new javax.swing.JLabel();
        cultistPlayerVar = new javax.swing.JLabel();
        numCultist = new javax.swing.JLabel();
        numCultistVar = new javax.swing.JLabel();
        visibleTreasures = new javax.swing.JPanel();
        hiddenTreasures = new javax.swing.JPanel();
        makeVisible = new javax.swing.JButton();
        stealTreasure = new javax.swing.JButton();
        discardTreasures = new javax.swing.JButton();
        discardAllTreasures = new javax.swing.JButton();

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Nombre");
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        name.setName(""); // NOI18N

        Atributos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Atributos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        nivel.setForeground(new java.awt.Color(0, 0, 0));
        nivel.setText("Nivel: ");

        combatLevel.setForeground(new java.awt.Color(0, 0, 0));
        combatLevel.setText("Nivel de combate:");

        nivelVar.setForeground(new java.awt.Color(0, 0, 0));
        nivelVar.setText("10");

        combatLevelVar.setForeground(new java.awt.Color(0, 0, 0));
        combatLevelVar.setText("35");

        death.setForeground(new java.awt.Color(0, 0, 0));
        death.setText("Estado:");

        deathVar.setForeground(new java.awt.Color(0, 0, 0));
        deathVar.setText("Muerto");

        canISteal.setForeground(new java.awt.Color(0, 0, 0));
        canISteal.setText("¿Puedo robar?:");

        canIStealVar.setForeground(new java.awt.Color(0, 0, 0));
        canIStealVar.setText("Si");

        enemy.setForeground(new java.awt.Color(0, 0, 0));
        enemy.setText("Enemigo:");

        enemyVar.setForeground(new java.awt.Color(0, 0, 0));
        enemyVar.setText("nombre");

        javax.swing.GroupLayout AtributosLayout = new javax.swing.GroupLayout(Atributos);
        Atributos.setLayout(AtributosLayout);
        AtributosLayout.setHorizontalGroup(
            AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addComponent(enemy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyVar))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(nivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nivelVar))
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(death)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deathVar)))
                        .addGap(23, 23, 23)
                        .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(combatLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combatLevelVar))
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(canISteal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(canIStealVar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AtributosLayout.setVerticalGroup(
            AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivel)
                    .addComponent(combatLevel)
                    .addComponent(nivelVar)
                    .addComponent(combatLevelVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(death)
                    .addComponent(deathVar)
                    .addComponent(canISteal)
                    .addComponent(canIStealVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemy, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(enemyVar)))
        );

        pendingBadConsequence.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Mal rollo pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout pendingBadConsequenceLayout = new javax.swing.GroupLayout(pendingBadConsequence);
        pendingBadConsequence.setLayout(pendingBadConsequenceLayout);
        pendingBadConsequenceLayout.setHorizontalGroup(
            pendingBadConsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pendingBadConsequenceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pendingBadConsequenceVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pendingBadConsequenceLayout.setVerticalGroup(
            pendingBadConsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendingBadConsequenceVar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        cultistInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Informacion de sectarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        cultistPlayer.setForeground(new java.awt.Color(0, 0, 0));
        cultistPlayer.setText("¿Soy sectario?:");

        cultistPlayerVar.setForeground(new java.awt.Color(0, 0, 0));
        cultistPlayerVar.setText("No");

        numCultist.setForeground(new java.awt.Color(0, 0, 0));
        numCultist.setText("Numero de sectarios en la partida:");

        numCultistVar.setForeground(new java.awt.Color(0, 0, 0));
        numCultistVar.setText("0");

        javax.swing.GroupLayout cultistInfoLayout = new javax.swing.GroupLayout(cultistInfo);
        cultistInfo.setLayout(cultistInfoLayout);
        cultistInfoLayout.setHorizontalGroup(
            cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cultistInfoLayout.createSequentialGroup()
                .addGroup(cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cultistInfoLayout.createSequentialGroup()
                        .addComponent(cultistPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cultistPlayerVar))
                    .addGroup(cultistInfoLayout.createSequentialGroup()
                        .addComponent(numCultist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numCultistVar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cultistInfoLayout.setVerticalGroup(
            cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cultistInfoLayout.createSequentialGroup()
                .addGroup(cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cultistPlayer)
                    .addComponent(cultistPlayerVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCultist)
                    .addComponent(numCultistVar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        visibleTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Tesoros visibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Tesoros ocultos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        makeVisible.setBackground(new java.awt.Color(153, 0, 153));
        makeVisible.setForeground(new java.awt.Color(255, 255, 255));
        makeVisible.setText("Hacer visibles");
        makeVisible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makeVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeVisibleActionPerformed(evt);
            }
        });

        stealTreasure.setBackground(new java.awt.Color(153, 0, 153));
        stealTreasure.setForeground(new java.awt.Color(255, 255, 255));
        stealTreasure.setText("Robar tesoro");
        stealTreasure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stealTreasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stealTreasureActionPerformed(evt);
            }
        });

        discardTreasures.setBackground(new java.awt.Color(153, 0, 153));
        discardTreasures.setForeground(new java.awt.Color(255, 255, 255));
        discardTreasures.setText("Descartar tesoros");
        discardTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        discardTreasures.setPreferredSize(new java.awt.Dimension(147, 28));
        discardTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardTreasuresActionPerformed(evt);
            }
        });

        discardAllTreasures.setBackground(new java.awt.Color(204, 0, 0));
        discardAllTreasures.setForeground(new java.awt.Color(255, 255, 255));
        discardAllTreasures.setText("Descartar todos los tesoros");
        discardAllTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        discardAllTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardAllTreasuresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cultistInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pendingBadConsequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Atributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(makeVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stealTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discardTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discardAllTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visibleTreasures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(discardTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(makeVisible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stealTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discardAllTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingBadConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cultistInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void discardTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardTreasuresActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        
        napakalakiModel.discardHiddenTreasures(selHidden);
        napakalakiModel.discardVisibleTreasures(selVisible);
        
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_discardTreasuresActionPerformed

    private void stealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stealTreasureActionPerformed
        if(playerModel.canISteal()){
            playerModel.stealTreasure();
            setPlayer(napakalakiModel.getCurrentPlayer());
        }
    }//GEN-LAST:event_stealTreasureActionPerformed

    private void makeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeVisibleActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakiModel.makeTreasuresVisible(selHidden);
        setPlayer(napakalakiModel.getCurrentPlayer());
        
    }//GEN-LAST:event_makeVisibleActionPerformed

    private void discardAllTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardAllTreasuresActionPerformed
        playerModel.discardAllTreasures();
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_discardAllTreasuresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atributos;
    private javax.swing.JLabel canISteal;
    private javax.swing.JLabel canIStealVar;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel combatLevelVar;
    private javax.swing.JPanel cultistInfo;
    private javax.swing.JLabel cultistPlayer;
    private javax.swing.JLabel cultistPlayerVar;
    private javax.swing.JLabel death;
    private javax.swing.JLabel deathVar;
    private javax.swing.JButton discardAllTreasures;
    private javax.swing.JButton discardTreasures;
    private javax.swing.JLabel enemy;
    private javax.swing.JLabel enemyVar;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JButton makeVisible;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nivelVar;
    private javax.swing.JLabel numCultist;
    private javax.swing.JLabel numCultistVar;
    private javax.swing.JPanel pendingBadConsequence;
    private GUI.PendingBadConsequenceView pendingBadConsequenceVar;
    private javax.swing.JButton stealTreasure;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
