/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JPanel;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author Lenovo
 */
public class PlayerView extends javax.swing.JPanel {
    //Atributo
    Player playerModel;
    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void setPlayer(Player aPlayer){
        playerModel = aPlayer;
        this.name.setText(playerModel.getName());
        this.nivelVar.setText(Integer.toString(playerModel.getLevels()));
        this.combatLevelVar.setText(Integer.toString(playerModel.getCombatLevel()));
        this.canIStealVar.setText(Boolean.toString(playerModel.canISteal()));
        this.enemyVar.setText(playerModel.enemy.getName());
        this.deathVar.setText(Boolean.toString(playerModel.isDead()));
        this.pendingBadConsequenceVar.setText(playerModel.pendingBadConsequence.toString());
        
        this.fillTreasurePanel(visibleTreasures,playerModel.getVisibleTreasures());
        this.fillTreasurePanel(hiddenTreasures,playerModel.getHiddenTreasures());
        
        repaint();
        revalidate();
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al panel
        for (Treasure t : aList) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        Atributos = new javax.swing.JPanel();
        nivel = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        nivelVar = new javax.swing.JLabel();
        combatLevelVar = new javax.swing.JLabel();
        death = new javax.swing.JLabel();
        deathVar = new javax.swing.JLabel();
        canISteal = new javax.swing.JLabel();
        canIStealVar = new javax.swing.JLabel();
        enemy = new javax.swing.JLabel();
        enemyVar = new javax.swing.JLabel();
        pendingBadConsequence = new javax.swing.JPanel();
        pendingBadConsequenceVar = new javax.swing.JLabel();
        cultistInfo = new javax.swing.JPanel();
        cultistPlayer = new javax.swing.JLabel();
        cultistPlayerVar = new javax.swing.JLabel();
        numCultist = new javax.swing.JLabel();
        numCultistVar = new javax.swing.JLabel();
        visibleTreasures = new javax.swing.JPanel();
        hiddenTreasures = new javax.swing.JPanel();
        makeVisible = new javax.swing.JButton();
        stealTreasure = new javax.swing.JButton();
        discardTreasures = new javax.swing.JButton();
        discardAllTreasures = new javax.swing.JButton();

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setText("Nombre");
        name.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        name.setName(""); // NOI18N

        Atributos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()), "Atributos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        nivel.setForeground(new java.awt.Color(0, 0, 0));
        nivel.setText("Nivel: ");

        combatLevel.setForeground(new java.awt.Color(0, 0, 0));
        combatLevel.setText("Nivel de combate:");

        nivelVar.setForeground(new java.awt.Color(0, 0, 0));
        nivelVar.setText("10");

        combatLevelVar.setForeground(new java.awt.Color(0, 0, 0));
        combatLevelVar.setText("35");

        death.setForeground(new java.awt.Color(0, 0, 0));
        death.setText("Estado:");

        deathVar.setForeground(new java.awt.Color(0, 0, 0));
        deathVar.setText("Muerto");

        canISteal.setForeground(new java.awt.Color(0, 0, 0));
        canISteal.setText("¿Puedo robar?:");

        canIStealVar.setForeground(new java.awt.Color(0, 0, 0));
        canIStealVar.setText("Si");

        enemy.setForeground(new java.awt.Color(0, 0, 0));
        enemy.setText("Enemigo:");

        enemyVar.setForeground(new java.awt.Color(0, 0, 0));
        enemyVar.setText("nombre");

        javax.swing.GroupLayout AtributosLayout = new javax.swing.GroupLayout(Atributos);
        Atributos.setLayout(AtributosLayout);
        AtributosLayout.setHorizontalGroup(
            AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addComponent(enemy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyVar))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(nivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nivelVar))
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(death)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deathVar)))
                        .addGap(23, 23, 23)
                        .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(combatLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combatLevelVar))
                            .addGroup(AtributosLayout.createSequentialGroup()
                                .addComponent(canISteal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(canIStealVar)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        AtributosLayout.setVerticalGroup(
            AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivel)
                    .addComponent(combatLevel)
                    .addComponent(nivelVar)
                    .addComponent(combatLevelVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(death)
                    .addComponent(deathVar)
                    .addComponent(canISteal)
                    .addComponent(canIStealVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemy, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(enemyVar)))
        );

        pendingBadConsequence.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()), "Mal rollo pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        pendingBadConsequenceVar.setForeground(new java.awt.Color(0, 0, 0));
        pendingBadConsequenceVar.setText("Mal rollo");

        javax.swing.GroupLayout pendingBadConsequenceLayout = new javax.swing.GroupLayout(pendingBadConsequence);
        pendingBadConsequence.setLayout(pendingBadConsequenceLayout);
        pendingBadConsequenceLayout.setHorizontalGroup(
            pendingBadConsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendingBadConsequenceVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pendingBadConsequenceLayout.setVerticalGroup(
            pendingBadConsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendingBadConsequenceVar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );

        cultistInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()), "Informacion de sectarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        cultistPlayer.setForeground(new java.awt.Color(0, 0, 0));
        cultistPlayer.setText("¿Soy sectario?:");

        cultistPlayerVar.setForeground(new java.awt.Color(0, 0, 0));
        cultistPlayerVar.setText("No");

        numCultist.setForeground(new java.awt.Color(0, 0, 0));
        numCultist.setText("Numero de sectarios en la partida:");

        numCultistVar.setForeground(new java.awt.Color(0, 0, 0));
        numCultistVar.setText("0");

        javax.swing.GroupLayout cultistInfoLayout = new javax.swing.GroupLayout(cultistInfo);
        cultistInfo.setLayout(cultistInfoLayout);
        cultistInfoLayout.setHorizontalGroup(
            cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cultistInfoLayout.createSequentialGroup()
                .addGroup(cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cultistInfoLayout.createSequentialGroup()
                        .addComponent(cultistPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cultistPlayerVar))
                    .addGroup(cultistInfoLayout.createSequentialGroup()
                        .addComponent(numCultist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numCultistVar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cultistInfoLayout.setVerticalGroup(
            cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cultistInfoLayout.createSequentialGroup()
                .addGroup(cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cultistPlayer)
                    .addComponent(cultistPlayerVar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cultistInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCultist)
                    .addComponent(numCultistVar)))
        );

        visibleTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()), "Tesoros visibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()), "Tesoros ocultos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Viner Hand ITC", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        makeVisible.setForeground(new java.awt.Color(0, 0, 0));
        makeVisible.setText("Make Visible");
        makeVisible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        stealTreasure.setForeground(new java.awt.Color(0, 0, 0));
        stealTreasure.setText("Steal Treasure");
        stealTreasure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        discardTreasures.setForeground(new java.awt.Color(0, 0, 0));
        discardTreasures.setText("Discard Treasures");
        discardTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        discardAllTreasures.setForeground(new java.awt.Color(0, 0, 0));
        discardAllTreasures.setText("Discard All Treasures");
        discardAllTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Atributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cultistInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pendingBadConsequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(makeVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stealTreasure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discardTreasures)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stealTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discardTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discardAllTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pendingBadConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cultistInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atributos;
    private javax.swing.JLabel canISteal;
    private javax.swing.JLabel canIStealVar;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel combatLevelVar;
    private javax.swing.JPanel cultistInfo;
    private javax.swing.JLabel cultistPlayer;
    private javax.swing.JLabel cultistPlayerVar;
    private javax.swing.JLabel death;
    private javax.swing.JLabel deathVar;
    private javax.swing.JButton discardAllTreasures;
    private javax.swing.JButton discardTreasures;
    private javax.swing.JLabel enemy;
    private javax.swing.JLabel enemyVar;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JButton makeVisible;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nivelVar;
    private javax.swing.JLabel numCultist;
    private javax.swing.JLabel numCultistVar;
    private javax.swing.JPanel pendingBadConsequence;
    private javax.swing.JLabel pendingBadConsequenceVar;
    private javax.swing.JButton stealTreasure;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
